#!/bin/bash
set -e


#

export fu_NUM_WORKER_THREADS=0

echo ""
echo "Collecting memory stats ..."
echo ""

for i in "$@"
do
  git show $i --oneline --no-patch
  "./bin/fu-debug-$i" src/cli.fu | grep -E 'STAT|allocs'
  echo ""
done
