#!/bin/bash
set -e

sed_i() {
  if [[ "$OSTYPE" == "darwin"* ]]
  then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}


# We'll be checking out each individual commit we want to bench,
#  so it'd be nice if we restored the original git branch
#   when we're done here.

CLEANUP_must_restore_git_branch=false
CLEANUP_must_restore_profiler_fu=false
CLEANUP_must_restore_SELF_TEST=false

do_clean_up () {

  # Restore initial git branch on fail/early exit.
  if [ "$CLEANUP_must_restore_git_branch" = true ]
  then
    CLEANUP_must_restore_git_branch=false
    git checkout -
  fi

  # Disable profiler.
  if [ "$CLEANUP_must_restore_profiler_fu" = true ]
  then
    CLEANUP_must_restore_profiler_fu=false
    sed_i 's/!!!!!!1/!!false/g' ./src/profiler.fu
  fi

  # Re-enable SELF_TEST mode.
  if [ "$CLEANUP_must_restore_SELF_TEST" = true ]
  then
    CLEANUP_must_restore_SELF_TEST=false
    sed_i 's/!!!101/!!true/g' ./src/fail.fu
  fi
}


# On exit -

clean_up () {
  ARG=$?

  # Restore initial git branch on fail/early exit.
  do_clean_up

  # Remove any intermediate build artifacts.
  if test -f "bin/fu.temp"
  then
    rm ./bin/fu.temp
  fi

  # Goodbye!
  echo ""
  echo "All done."
  echo ""

  exit $ARG
}

trap clean_up EXIT


# For each commit, unless a build is already available,
#  check out and build third-gen release and debug compilers.
#
# Third gen is overkill - unless something is broken,
#  third-gen should be byte-equal to second-gen.

for i in "$@"
do
  echo ""
  echo "Preparing bin/fu-$i ..."

  if test -f "bin/fu-$i"
  then
    echo "   SKIP Already exists."
  else

    git checkout $i
    CLEANUP_must_restore_git_branch=true

    # Disable SELF_TEST mode.
    sed_i 's/!!true/!!!101/g' ./src/fail.fu
    CLEANUP_must_restore_SELF_TEST=true

    # Suppress some warnings.
    sed_i 's/-Wno-dangling-reference //g' ./src/build.fu
    sed_i 's/-Wno-float-conversion /-Wno-float-conversion -Wno-dangling-reference /g' ./src/build.fu
    CLEANUP_must_restore_SELF_TEST=true

    #
    ./bin/fu.works --bin bin/fu.temp src/cli.fu
    ./bin/fu.temp  --bin bin/fu.temp src/cli.fu
    ./bin/fu.temp  --bin "bin/fu-$i" src/cli.fu

    # Enable memory profiling.
    sed_i 's/!!false/!!!!!!1/g' ./src/profiler.fu
    CLEANUP_must_restore_profiler_fu=true

    # Allocation counters currently only work for debug builds.
    ./bin/fu.temp  --debug --bin "bin/fu-debug-$i" src/cli.fu

    # Go back to whatever branch we were on when we started.
    do_clean_up

    echo "     OK bin/fu-$i."
  fi
done
