#!/bin/bash
set -e

echo ""
echo "        ################################"
echo ""
echo "        Reset & Bootstrap ..."
echo ""

git reset
git checkout *.fu.cpp *.fu.unity.cpp
./bootstrap
mv ./bin/fu ./bin/fu.works

./cycle
