#!/bin/bash
set -e

git reset
git checkout *.fu.cpp *.fu.unity.cpp *akeLists.txt
./bootstrap

mv testdiff/now.td testdiff/next.td
mv testdiff/prev.td testdiff/now.td

./bin/fu self

mv testdiff/now.td testdiff/prev.td
mv testdiff/next.td testdiff/now.td

./bin/fu self
./bin/fu self
./bin/fu self
